// pages/api/reviews.js  (or  app/api/reviews/route.js for App Router)
// ------------------------------------------------------------------
// POST /api/reviews  — saves a ResourceReview to the database.
// Adjust the DB client import to match your Supabase/Postgres setup.
// ------------------------------------------------------------------

// ── Supabase example ──────────────────────────────────────────────
// import { createClient } from "@supabase/supabase-js";
// const supabase = createClient(
//   process.env.NEXT_PUBLIC_SUPABASE_URL,
//   process.env.SUPABASE_SERVICE_ROLE_KEY
// );

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const {
    resourceId,
    attended,
    didNotAttendReason,
    rating,
    waitTimeMinutes,
    informationAccurate,
    text,
    shareTextWithResource,
    photoUrl,
    photoPublic,
    createdAt,
  } = req.body;

  // Basic validation
  if (!resourceId) {
    return res.status(400).json({ error: "resourceId is required" });
  }

  // Build the review object matching the ResourceReview schema
  const review = {
    // id auto-generated by DB
    resourceId,
    attended: attended ?? null,
    didNotAttendReason: attended === false ? didNotAttendReason || null : null,
    rating: attended === true ? (rating || null) : null,
    waitTimeMinutes: attended === true ? (waitTimeMinutes ?? null) : null,
    informationAccurate: informationAccurate ?? null,
    text: text && text.trim().length > 0 ? text.trim() : null,
    shareTextWithResource: shareTextWithResource === true,
    photoUrl: photoUrl || null,
    photoPublic: photoUrl ? (photoPublic === true) : null,
    createdAt: createdAt || new Date().toISOString(),
    deletedAt: null,
    // authorId should come from the session/auth in production
    // authorId: req.session?.userId || "anonymous",
  };

  try {
    // ── Supabase insert ───────────────────────────────────────────
    // const { data, error } = await supabase.from("reviews").insert([review]).select().single();
    // if (error) throw error;
    // return res.status(201).json(data);

    // ── Placeholder response (remove once DB is wired up) ─────────
    console.log("Review payload:", review);
    return res.status(201).json({ ok: true, review });
  } catch (err) {
    console.error("Error saving review:", err);
    return res.status(500).json({ error: "Failed to save review" });
  }
}
